#Minecraft server properties
#Wed Mar 18 11:02:35 CDT 2026
allow-flight=false
allow-nether=true
level-name=world
level-seed=
max-players=20
online-mode=false
pvp=true
server-ip=
server-port=25565
spawn-animals=true
spawn-monsters=true
view-distance=10
white-list=false
